### ISSUE TITLE
Upload raw sensor data to S3 bucket

### ISSUE THREAD

**Issue by mitp19** [stremler-research/openactigraphy-fitbit-watchface#3]

**Comment by mitp19** [comment]
@vfcosta, I pushed some code that sends a file with sensor data from the fitbit device to fitbit companion, can you create the API required to upload the data from the fitbit companion to AWS via a pre-signed URL.

**Comment by mitp19** [comment]
You should be able to do this using the Fitbit OS simulator. Login using the settings page and that will trigger the reading of the data from the sensors.

**Comment by vfcosta** [comment]
I´m getting some errors:
Error: Couldn't open file: RawDataLogger-20190109.txt
Error: Upload failed, error 403

**Comment by vfcosta** [comment]
https://docs.aws.amazon.com/apigateway/latest/developerguide/apigateway-enable-cognito-user-pool.html

**Comment by vfcosta** [comment]
Changing the scope from email to openid in the settings component makes the id_token to be returned from aws.

**Comment by vfcosta** [comment]
Need to confirm if the fetch method from fitbit is able to upload files.
I couldn´t find a way to use it to send files to s3.
We may need to use an alternative solution for uploads.

**Comment by vfcosta** [comment]
It´s working. The issue was with the bucket permissions.
